# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Robot Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10ss
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install -r resources/configuration/requirements.txt
        python3 -m pip install webdrivermanager
        webdrivermanager firefox chrome
    - name: Test with robot
      run: |
         robot -d reports./test_suite
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
         name: reports
         path: reports
        
  generate_report:
      permissions:
        actions: write
        issues: write
        discussions: write
        pull-requests: write

      if: always()
      with:
        needs: [reports ]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Download reportsChrome
          uses: actions/download-artifact@v3
          with:
              name: Final Report
              path: reports
        - name: Send report to commit
          uses: SanthoshJeeva440/robotframework_selenium@2.3
          with:
              gh_access_token: ${{ secrets.GITHUB_TOKEN }}
              show_passed_tests: false